name: Composite Action 1
description: Tests env inheritance
runs:
  using: composite
  steps:
    - run: echo Hello ${{ env.MYVAR }}
      shell: bash
    - run: echo "OTHERVAR=testing" >> $GITHUB_ENV
      shell: bash
