on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to print'
        required: false
jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: Hello World
    environment: "playground"
    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: |
          echo "Hello, ${{ inputs.name || 'World' }}!"
