on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: Hello World
    env:
      MYVAR: "WORLD"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-composite
      - run: echo ${{ env.OTHERVAR }}